/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#45474c',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#005236',
        'on-secondary-fixed': '#002113',
        'on-primary-fixed-variant': '#3c475a',
        'surface-container-high': '#dce9ff',
        'on-error': '#ffffff',
        'tertiary': '#201100',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-container': '#3c2300',
        'on-primary-container': '#8590a6',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#bcc7de',
        'on-tertiary-fixed-variant': '#653e00',
        'outline': '#75777d',
        'on-primary-fixed': '#111c2d',
        'surface': '#f8f9ff',
        'surface-container-low': '#eff4ff',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#4edea3',
        'primary': '#091426',
        'on-secondary': '#ffffff',
        'background': '#f8f9ff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary': '#006c49',
        'inverse-surface': '#213145',
        'on-tertiary-container': '#c88000',
        'surface-bright': '#f8f9ff',
        'on-error-container': '#93000a',
        'on-background': '#0b1c30',
        'primary-fixed-dim': '#bcc7de',
        'error': '#ba1a1a',
        'primary-container': '#1e293b',
        'on-surface': '#0b1c30',
        'surface-container-highest': '#d3e4fe',
        'outline-variant': '#c5c6cd',
        'error-container': '#ffdad6',
        'surface-tint': '#545f73',
        'surface-variant': '#d3e4fe',
        'surface-container': '#e5eeff',
        'secondary-fixed': '#6ffbbe',
        'primary-fixed': '#d8e3fb',
        'tertiary-fixed': '#ffddb8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '1.5rem',
        'stack-lg': '1.5rem',
        'container-max-width': '1440px',
        'margin-page': '2rem',
        'stack-md': '1rem',
        'sidebar-width': '260px',
        'stack-sm': '0.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
